/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lv.maska;

public class App {
    public static void main(String[] args) {
        //new Processor();
        new HttpService(8080);
    }
}
